### Introduction To Pandas Module
Here, we are learning data analysis. Pandas is a software library written for the Python programming language that helps with data manipulation and analysis. It offers various data structures which help in the manipulation of data. <br>
One of the data structures used is DataFrame.<br>
DataFrame is used as a way to store data in a rectangular grid.<br>
Similar to how data is stored in Microsoft Excel.
### Installation
We can easily install this library using the terminal. Follow the steps given below to install Pandas:<br>
Step 1: Go to the Windows PowerShell.<br>
Step 2: We can install pandas with the help of pip easily. Head over to the directory where you want to install the pandas and fire the below command:<br>
__pip install pandas__<br>
This is very simple to install.

In [86]:
# !pip install pandas

### Other way to install
If the above steps do not work for you, here is another way to install:<br>
Step 1: Go to your browser. Search for __python unofficial binaries__, or click <br>
https://www.lfd.uci.edu/~gohlke/pythonlibs/<br> 
and you will be redirected to the binary page.<br>
Step 2: To download the library, search for pandas – Ctrl + F will help you. Download pandas library based on your python version. <br>
Step 3: After the installation, head over to the directory where you've downloaded the pandas. <br>
Step 4: Right-click to open Windows PowerShell. Pip can help us with the installation. Just go to that location in your terminal and run the following command: <br>
__pip install pandas__ <br>
Complete this command by the TAB button so that the location of your folder is mentioned.

### import pandas
Once Pandas is installed, import it in your applications by adding the import keyword:<br>
__import pandas as pd__<br>
Now Pandas is imported and ready to use.

In [87]:
import pandas

In [88]:
students = {
    'Name': ["Daniyal Basharat", " M Abdullah", "Muhammad Abid", "Shumail Khan","Qasim Ali"],
    'Marks': [80, 72, 77, 65, 15],
    'Class':["1st Year", "2nd Year", "1st Year", "3rd Year", "2nd Year"],
    'Age': [20, 21, 19, 22, 21]
}

In [89]:
df = pandas.DataFrame(students)

In [90]:
df

               Name  Marks     Class  Age
0  Daniyal Basharat     80  1st Year   20
1        M Abdullah     72  2nd Year   21
2     Muhammad Abid     77  1st Year   19
3      Shumail Khan     65  3rd Year   22
4         Qasim Ali     15  2nd Year   21

### Pandas as pd
Pandas is usually imported under the pd alias.
#### alias: 
In Python alias are an alternate name for referring to the same thing.<br>
Create an alias with the as keyword while importing:<br>
__import pandas as pd__<br>
Now the Pandas package can be referred to as pd instead of pandas.

In [91]:
import pandas as pd

In [92]:
df = pd.DataFrame(students)

In [93]:
df

               Name  Marks     Class  Age
0  Daniyal Basharat     80  1st Year   20
1        M Abdullah     72  2nd Year   21
2     Muhammad Abid     77  1st Year   19
3      Shumail Khan     65  3rd Year   22
4         Qasim Ali     15  2nd Year   21

### Checking Pandas Version
The version string is stored under __version__ attribute.

In [94]:
pd.__version__

'3.0.3'

## Saving to CSV and other extensions like excel

In [95]:
df.to_csv('pythonMonday.csv')

## Remove Index and saving the csv file

In [96]:
df.to_csv('pythonMondayRemoveIndex.csv', index=False)

## Show some rows from the Start

In [97]:
df.head()

               Name  Marks     Class  Age
0  Daniyal Basharat     80  1st Year   20
1        M Abdullah     72  2nd Year   21
2     Muhammad Abid     77  1st Year   19
3      Shumail Khan     65  3rd Year   22
4         Qasim Ali     15  2nd Year   21

## Specify No of rows to show

In [98]:
df.head(3)

               Name  Marks     Class  Age
0  Daniyal Basharat     80  1st Year   20
1        M Abdullah     72  2nd Year   21
2     Muhammad Abid     77  1st Year   19

In [99]:
df.tail(3)

            Name  Marks     Class  Age
2  Muhammad Abid     77  1st Year   19
3   Shumail Khan     65  3rd Year   22
4      Qasim Ali     15  2nd Year   21

In [100]:
df.tail()

               Name  Marks     Class  Age
0  Daniyal Basharat     80  1st Year   20
1        M Abdullah     72  2nd Year   21
2     Muhammad Abid     77  1st Year   19
3      Shumail Khan     65  3rd Year   22
4         Qasim Ali     15  2nd Year   21

In [101]:
df.describe()

           Marks        Age
count   5.000000   5.000000
mean   61.800000  20.600000
std    26.771253   1.140175
min    15.000000  19.000000
25%    65.000000  20.000000
50%    72.000000  21.000000
75%    77.000000  21.000000
max    80.000000  22.000000

# Reading csv or other files

In [102]:
classData= pd.read_csv("pythonMondayRemoveIndex.csv")
classData

               Name  Marks     Class  Age
0  Daniyal Basharat     80  1st Year   20
1        M Abdullah     72  2nd Year   21
2     Muhammad Abid     77  1st Year   19
3      Shumail Khan     65  3rd Year   22
4         Qasim Ali     15  2nd Year   21

In [103]:
classData= pd.read_csv("pythonMonday.csv")
classData

   Unnamed: 0              Name  Marks     Class  Age
0           0  Daniyal Basharat     80  1st Year   20
1           1        M Abdullah     72  2nd Year   21
2           2     Muhammad Abid     77  1st Year   19
3           3      Shumail Khan     65  3rd Year   22
4           4         Qasim Ali     15  2nd Year   21

In [104]:
classData.drop('Name', axis=1)

   Unnamed: 0  Marks     Class  Age
0           0     80  1st Year   20
1           1     72  2nd Year   21
2           2     77  1st Year   19
3           3     65  3rd Year   22
4           4     15  2nd Year   21

In [105]:
classData

   Unnamed: 0              Name  Marks     Class  Age
0           0  Daniyal Basharat     80  1st Year   20
1           1        M Abdullah     72  2nd Year   21
2           2     Muhammad Abid     77  1st Year   19
3           3      Shumail Khan     65  3rd Year   22
4           4         Qasim Ali     15  2nd Year   21

In [106]:
classData.drop(0, axis=0)

   Unnamed: 0           Name  Marks     Class  Age
1           1     M Abdullah     72  2nd Year   21
2           2  Muhammad Abid     77  1st Year   19
3           3   Shumail Khan     65  3rd Year   22
4           4      Qasim Ali     15  2nd Year   21

In [107]:
classData

   Unnamed: 0              Name  Marks     Class  Age
0           0  Daniyal Basharat     80  1st Year   20
1           1        M Abdullah     72  2nd Year   21
2           2     Muhammad Abid     77  1st Year   19
3           3      Shumail Khan     65  3rd Year   22
4           4         Qasim Ali     15  2nd Year   21

# Check the spelling

In [108]:
classData['Class']

0    1st Year
1    2nd Year
2    1st Year
3    3rd Year
4    2nd Year
Name: Class, dtype: str

# Check the trail space

In [109]:
classData.columns = classData.columns.str.strip().str.lower()

In [110]:
classData['class']

0    1st Year
1    2nd Year
2    1st Year
3    3rd Year
4    2nd Year
Name: class, dtype: str

# Corrected Spelling

In [111]:
classData['name']

0    Daniyal Basharat
1          M Abdullah
2       Muhammad Abid
3        Shumail Khan
4           Qasim Ali
Name: name, dtype: str

# Check the head space

In [112]:
classData['name']

0    Daniyal Basharat
1          M Abdullah
2       Muhammad Abid
3        Shumail Khan
4           Qasim Ali
Name: name, dtype: str

In [113]:
type(classData['name'])

pandas.Series

In [114]:
classData['age']

0    20
1    21
2    19
3    22
4    21
Name: age, dtype: int64

classData['gpa'][0]

In [115]:
classData['age'][0]

np.int64(20)

In [116]:
classData['age'][0]=90

C:\Users\engin\AppData\Local\Temp\ipykernel_20476\3711599208.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  classData['age'][0]=90

In [117]:
classData

   unnamed: 0              name  marks     class  age
0           0  Daniyal Basharat     80  1st Year   20
1           1        M Abdullah     72  2nd Year   21
2           2     Muhammad Abid     77  1st Year   19
3           3      Shumail Khan     65  3rd Year   22
4           4         Qasim Ali     15  2nd Year   21

In [118]:
classData['age'][4]

np.int64(21)

In [119]:
classData['age'][4]=5

C:\Users\engin\AppData\Local\Temp\ipykernel_20476\2197085196.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  classData['age'][4]=5

In [120]:
classData["name"][4]

'Qasim Ali'

# Rename the column name

In [121]:
classData.rename(columns={'age': 'AGE'})

   unnamed: 0              name  marks     class  AGE
0           0  Daniyal Basharat     80  1st Year   20
1           1        M Abdullah     72  2nd Year   21
2           2     Muhammad Abid     77  1st Year   19
3           3      Shumail Khan     65  3rd Year   22
4           4         Qasim Ali     15  2nd Year   21

## Create Labels
With the index argument, you can name your own labels.

In [122]:
classData.index = ["First","Second", "Third", "Fourth", "Fifth"]
classData

        unnamed: 0              name  marks     class  age
First            0  Daniyal Basharat     80  1st Year   20
Second           1        M Abdullah     72  2nd Year   21
Third            2     Muhammad Abid     77  1st Year   19
Fourth           3      Shumail Khan     65  3rd Year   22
Fifth            4         Qasim Ali     15  2nd Year   21

# Asignment

In [123]:
classdata = classData.drop('unnamed: 0', axis=1)
classData

        unnamed: 0              name  marks     class  age
First            0  Daniyal Basharat     80  1st Year   20
Second           1        M Abdullah     72  2nd Year   21
Third            2     Muhammad Abid     77  1st Year   19
Fourth           3      Shumail Khan     65  3rd Year   22
Fifth            4         Qasim Ali     15  2nd Year   21

# Inplace

In [124]:
classData.drop('unnamed: 0', axis=1, inplace = True)
classData

                    name  marks     class  age
First   Daniyal Basharat     80  1st Year   20
Second        M Abdullah     72  2nd Year   21
Third      Muhammad Abid     77  1st Year   19
Fourth      Shumail Khan     65  3rd Year   22
Fifth          Qasim Ali     15  2nd Year   21

# Accessing the value in Dataframe

In [125]:
classData["name"]

First     Daniyal Basharat
Second          M Abdullah
Third        Muhammad Abid
Fourth        Shumail Khan
Fifth            Qasim Ali
Name: name, dtype: str

In [126]:
classData["name"]["Fifth"]

'Qasim Ali'

## Pandas 
Pandas is an open source data analysis library written in Python.<br>
It uses the power and speed of numpy to make data analysis and preprocessing easy for data scientists.<br>
__Pandas__ is used to analyze data.<br>
Python data analysis using pandas is a great start to Exploratory Data Analysis (EDA) for a data scientist.

## Pandas Data Structure
Panda has two types of Data Structure:<br> 
    a) Series<br>
    b) Dataframe
### Series
It is a one dimentional array with indexes. It stores a single column or row of data in a Dataframe.<br>
It is a one dimensional array capable of holding any type of data.
### Dataframe
It is a tabular spreadsheet like structure representing rows each of which contains one or more columns.<br>
It is a multi dimensional array capable of holding any type of data.<br>
__Series__ is like a column, a __DataFrame__ is the whole table.

In [127]:
classData['age']

First     20
Second    21
Third     19
Fourth    22
Fifth     21
Name: age, dtype: int64

In [128]:
type(classData['age'])

pandas.Series

In [129]:
classData

                    name  marks     class  age
First   Daniyal Basharat     80  1st Year   20
Second        M Abdullah     72  2nd Year   21
Third      Muhammad Abid     77  1st Year   19
Fourth      Shumail Khan     65  3rd Year   22
Fifth          Qasim Ali     15  2nd Year   21

In [130]:
type(classData)

pandas.DataFrame

In [131]:
import numpy as np

In [132]:
series1= pd.Series(np.random.rand())

In [133]:
series1

0    0.874972
dtype: float64

In [134]:
series1= pd.Series(np.random.rand(30))

In [135]:
series1

0     0.097697
1     0.588536
2     0.787561
3     0.507561
4     0.048638
5     0.100514
6     0.120288
7     0.838380
8     0.482490
9     0.092529
10    0.001102
11    0.653974
12    0.171169
13    0.028317
14    0.915243
15    0.730553
16    0.495784
17    0.903825
18    0.406022
19    0.311777
20    0.418028
21    0.532091
22    0.483505
23    0.408609
24    0.010729
25    0.849333
26    0.330769
27    0.949183
28    0.358859
29    0.207007
dtype: float64

In [136]:
type(series1)

pandas.Series

In [137]:
np.random.rand(3,4)

array([[0.04184206, 0.05617848, 0.35946073, 0.54999532],
       [0.29324058, 0.03096376, 0.79745978, 0.65480398],
       [0.72062732, 0.20695536, 0.79541918, 0.41126812]])

In [138]:
newDf = pd.DataFrame(np.random.rand(330,5))
# newDf = pd.DataFrame(np.random.rand(330,5), index=np.arange(330))

In [139]:
type(newDf)

pandas.DataFrame

In [140]:
newDf.head(2)

          0         1         2         3         4
0  0.506347  0.429578  0.436769  0.177261  0.091772
1  0.346077  0.673472  0.623099  0.799790  0.862662

In [141]:
newDf.tail(2)

            0         1         2         3         4
328  0.522949  0.129179  0.496525  0.672257  0.614697
329  0.486032  0.431836  0.961544  0.758247  0.719259

In [142]:
newDf.info()

<class 'pandas.DataFrame'>
RangeIndex: 330 entries, 0 to 329
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       330 non-null    float64
 1   1       330 non-null    float64
 2   2       330 non-null    float64
 3   3       330 non-null    float64
 4   4       330 non-null    float64
dtypes: float64(5)
memory usage: 13.0 KB

In [143]:
newDf.describe()

                0           1           2           3           4
count  330.000000  330.000000  330.000000  330.000000  330.000000
mean     0.526999    0.519031    0.483213    0.526818    0.493030
std      0.291112    0.284067    0.294347    0.283513    0.290378
min      0.004386    0.012630    0.003135    0.000270    0.002052
25%      0.307599    0.272818    0.220858    0.298282    0.222863
50%      0.530998    0.530886    0.490763    0.553924    0.494192
75%      0.788499    0.765990    0.745811    0.760060    0.748131
max      0.995911    0.992960    0.999883    0.998392    0.994235

In [144]:
newDf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

# Change the value inside the dataframe

In [145]:
newDf[0][0]= 10000.0

C:\Users\engin\AppData\Local\Temp\ipykernel_20476\1615845312.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  newDf[0][0]= 10000.0

In [146]:
newDf

            0         1         2         3         4
0    0.506347  0.429578  0.436769  0.177261  0.091772
1    0.346077  0.673472  0.623099  0.799790  0.862662
2    0.234967  0.246847  0.605068  0.377762  0.165425
3    0.873877  0.523773  0.114289  0.205897  0.932115
4    0.424802  0.527786  0.026125  0.907716  0.803409
..        ...       ...       ...       ...       ...
325  0.318888  0.683570  0.225811  0.629169  0.175035
326  0.400679  0.943985  0.749789  0.397487  0.875766
327  0.991202  0.473211  0.011192  0.421070  0.033817
328  0.522949  0.129179  0.496525  0.672257  0.614697
329  0.486032  0.431836  0.961544  0.758247  0.719259

[330 rows x 5 columns]

In [147]:
newDf.head()

          0         1         2         3         4
0  0.506347  0.429578  0.436769  0.177261  0.091772
1  0.346077  0.673472  0.623099  0.799790  0.862662
2  0.234967  0.246847  0.605068  0.377762  0.165425
3  0.873877  0.523773  0.114289  0.205897  0.932115
4  0.424802  0.527786  0.026125  0.907716  0.803409

# Transpose

In [148]:
newDf.T

,0,1,2,3,4,5,6,7,8,9,...,320,321,322,323,324,325,326,327,328,329
0,0.506347,0.346077,0.234967,0.873877,0.424802,0.104417,0.988118,0.307299,0.940676,0.886312,...,0.489722,0.263423,0.159806,0.349466,0.793825,0.318888,0.400679,0.991202,0.522949,0.486032
1,0.429578,0.673472,0.246847,0.523773,0.527786,0.558414,0.305818,0.783574,0.424041,0.855444,...,0.272250,0.728967,0.869845,0.616407,0.980509,0.683570,0.943985,0.473211,0.129179,0.431836
2,0.436769,0.623099,0.605068,0.114289,0.026125,0.065639,0.031720,0.865109,0.432628,0.126594,...,0.869828,0.885194,0.091355,0.456715,0.562113,0.225811,0.749789,0.011192,0.496525,0.961544
3,0.177261,0.799790,0.377762,0.205897,0.907716,0.719806,0.126999,0.564976,0.528777,0.223284,...,0.296803,0.702689,0.012777,0.290718,0.998392,0.629169,0.397487,0.421070,0.672257,0.758247
4,0.091772,0.862662,0.165425,0.932115,0.803409,0.563832,0.555468,0.043145,0.419581,0.991474,...,0.184497,0.263262,0.554646,0.312399,0.380672,0.175035,0.875766,0.033817,0.614697,0.719259

# Sorting

In [149]:
newDf.sort_index(axis=0)

            0         1         2         3         4
0    0.506347  0.429578  0.436769  0.177261  0.091772
1    0.346077  0.673472  0.623099  0.799790  0.862662
2    0.234967  0.246847  0.605068  0.377762  0.165425
3    0.873877  0.523773  0.114289  0.205897  0.932115
4    0.424802  0.527786  0.026125  0.907716  0.803409
..        ...       ...       ...       ...       ...
325  0.318888  0.683570  0.225811  0.629169  0.175035
326  0.400679  0.943985  0.749789  0.397487  0.875766
327  0.991202  0.473211  0.011192  0.421070  0.033817
328  0.522949  0.129179  0.496525  0.672257  0.614697
329  0.486032  0.431836  0.961544  0.758247  0.719259

[330 rows x 5 columns]

In [150]:
newDf.sort_index(axis=0, ascending=False)

            0         1         2         3         4
329  0.486032  0.431836  0.961544  0.758247  0.719259
328  0.522949  0.129179  0.496525  0.672257  0.614697
327  0.991202  0.473211  0.011192  0.421070  0.033817
326  0.400679  0.943985  0.749789  0.397487  0.875766
325  0.318888  0.683570  0.225811  0.629169  0.175035
..        ...       ...       ...       ...       ...
4    0.424802  0.527786  0.026125  0.907716  0.803409
3    0.873877  0.523773  0.114289  0.205897  0.932115
2    0.234967  0.246847  0.605068  0.377762  0.165425
1    0.346077  0.673472  0.623099  0.799790  0.862662
0    0.506347  0.429578  0.436769  0.177261  0.091772

[330 rows x 5 columns]

In [151]:
newDf.sort_index(axis=1)

            0         1         2         3         4
0    0.506347  0.429578  0.436769  0.177261  0.091772
1    0.346077  0.673472  0.623099  0.799790  0.862662
2    0.234967  0.246847  0.605068  0.377762  0.165425
3    0.873877  0.523773  0.114289  0.205897  0.932115
4    0.424802  0.527786  0.026125  0.907716  0.803409
..        ...       ...       ...       ...       ...
325  0.318888  0.683570  0.225811  0.629169  0.175035
326  0.400679  0.943985  0.749789  0.397487  0.875766
327  0.991202  0.473211  0.011192  0.421070  0.033817
328  0.522949  0.129179  0.496525  0.672257  0.614697
329  0.486032  0.431836  0.961544  0.758247  0.719259

[330 rows x 5 columns]

In [152]:
newDf.sort_index(axis=1, ascending=False)

            4         3         2         1         0
0    0.091772  0.177261  0.436769  0.429578  0.506347
1    0.862662  0.799790  0.623099  0.673472  0.346077
2    0.165425  0.377762  0.605068  0.246847  0.234967
3    0.932115  0.205897  0.114289  0.523773  0.873877
4    0.803409  0.907716  0.026125  0.527786  0.424802
..        ...       ...       ...       ...       ...
325  0.175035  0.629169  0.225811  0.683570  0.318888
326  0.875766  0.397487  0.749789  0.943985  0.400679
327  0.033817  0.421070  0.011192  0.473211  0.991202
328  0.614697  0.672257  0.496525  0.129179  0.522949
329  0.719259  0.758247  0.961544  0.431836  0.486032

[330 rows x 5 columns]

In [153]:
newDf.head()

          0         1         2         3         4
0  0.506347  0.429578  0.436769  0.177261  0.091772
1  0.346077  0.673472  0.623099  0.799790  0.862662
2  0.234967  0.246847  0.605068  0.377762  0.165425
3  0.873877  0.523773  0.114289  0.205897  0.932115
4  0.424802  0.527786  0.026125  0.907716  0.803409

In [154]:
newDf[0][1]

np.float64(0.34607651143728435)

In [155]:
type(newDf[0])

pandas.Series

In [156]:
newDf

            0         1         2         3         4
0    0.506347  0.429578  0.436769  0.177261  0.091772
1    0.346077  0.673472  0.623099  0.799790  0.862662
2    0.234967  0.246847  0.605068  0.377762  0.165425
3    0.873877  0.523773  0.114289  0.205897  0.932115
4    0.424802  0.527786  0.026125  0.907716  0.803409
..        ...       ...       ...       ...       ...
325  0.318888  0.683570  0.225811  0.629169  0.175035
326  0.400679  0.943985  0.749789  0.397487  0.875766
327  0.991202  0.473211  0.011192  0.421070  0.033817
328  0.522949  0.129179  0.496525  0.672257  0.614697
329  0.486032  0.431836  0.961544  0.758247  0.719259

[330 rows x 5 columns]

## view

In [157]:
newDfView=newDf

In [158]:
newDfView

            0         1         2         3         4
0    0.506347  0.429578  0.436769  0.177261  0.091772
1    0.346077  0.673472  0.623099  0.799790  0.862662
2    0.234967  0.246847  0.605068  0.377762  0.165425
3    0.873877  0.523773  0.114289  0.205897  0.932115
4    0.424802  0.527786  0.026125  0.907716  0.803409
..        ...       ...       ...       ...       ...
325  0.318888  0.683570  0.225811  0.629169  0.175035
326  0.400679  0.943985  0.749789  0.397487  0.875766
327  0.991202  0.473211  0.011192  0.421070  0.033817
328  0.522949  0.129179  0.496525  0.672257  0.614697
329  0.486032  0.431836  0.961544  0.758247  0.719259

[330 rows x 5 columns]

In [159]:
newDfView[0][0]=765

C:\Users\engin\AppData\Local\Temp\ipykernel_20476\4063526219.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  newDfView[0][0]=765

In [160]:
newDf.head()

          0         1         2         3         4
0  0.506347  0.429578  0.436769  0.177261  0.091772
1  0.346077  0.673472  0.623099  0.799790  0.862662
2  0.234967  0.246847  0.605068  0.377762  0.165425
3  0.873877  0.523773  0.114289  0.205897  0.932115
4  0.424802  0.527786  0.026125  0.907716  0.803409

In [161]:
newDfView.head()

          0         1         2         3         4
0  0.506347  0.429578  0.436769  0.177261  0.091772
1  0.346077  0.673472  0.623099  0.799790  0.862662
2  0.234967  0.246847  0.605068  0.377762  0.165425
3  0.873877  0.523773  0.114289  0.205897  0.932115
4  0.424802  0.527786  0.026125  0.907716  0.803409

In [162]:
newDfCopy=newDf.copy()

In [163]:
newDfCopy[0][0]=656

C:\Users\engin\AppData\Local\Temp\ipykernel_20476\2532441962.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  newDfCopy[0][0]=656

In [164]:
newDf.head()

          0         1         2         3         4
0  0.506347  0.429578  0.436769  0.177261  0.091772
1  0.346077  0.673472  0.623099  0.799790  0.862662
2  0.234967  0.246847  0.605068  0.377762  0.165425
3  0.873877  0.523773  0.114289  0.205897  0.932115
4  0.424802  0.527786  0.026125  0.907716  0.803409

In [165]:
newDfCopy.head()

          0         1         2         3         4
0  0.506347  0.429578  0.436769  0.177261  0.091772
1  0.346077  0.673472  0.623099  0.799790  0.862662
2  0.234967  0.246847  0.605068  0.377762  0.165425
3  0.873877  0.523773  0.114289  0.205897  0.932115
4  0.424802  0.527786  0.026125  0.907716  0.803409

In [166]:
import pandas as pd

# Create a sample DataFrame
data = {
    "Student": ["Ali", "Sara", "Bilal", "Hina"],
    "Marks": [85, 92, 76, 89],
    "Age": [20, 21, 19, 22]
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

Original DataFrame:
   Student  Marks  Age
0     Ali     85   20
1    Sara     92   21
2   Bilal     76   19
3    Hina     89   22

In [167]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Student  4 non-null      str
 1   Marks    4 non-null      int64
 2   Age      4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes
None

In [168]:
print("\nDescribe:\n", df.describe())

Describe:
            Marks        Age
count   4.000000   4.000000
mean   85.500000  20.500000
std     6.952218   1.290994
min    76.000000  19.000000
25%    82.750000  19.750000
50%    87.000000  20.500000
75%    89.750000  21.250000
max    92.000000  22.000000

In [169]:
# -----------------------------
# 2. SORTING
# -----------------------------
print("\nSorting by Marks (descending):\n", df.sort_values("Marks", ascending=False))
print("\nSorting by Age (ascending):\n", df.sort_values("Age"))

Sorting by Marks (descending):
   Student  Marks  Age
1    Sara     92   21
3    Hina     89   22
0     Ali     85   20
2   Bilal     76   19

Sorting by Age (ascending):
   Student  Marks  Age
2   Bilal     76   19
0     Ali     85   20
1    Sara     92   21
3    Hina     89   22

In [170]:
# -----------------------------
# 3. TRANSPOSE
# -----------------------------
print("\nTransposed DataFrame:\n", df.T)

Transposed DataFrame:
            0     1      2     3
Student  Ali  Sara  Bilal  Hina
Marks     85    92     76    89
Age       20    21     19    22

## Slicing through loc function

In [171]:
import pandas as pd

# Sample DataFrame
data = {
    "Name": ["Ali", "Sara", "Bilal", "Hina"],
    "Marks": [85, 92, 76, 89],
    "Age": [20, 21, 19, 22]
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

Original DataFrame:
     Name  Marks  Age
0    Ali     85   20
1   Sara     92   21
2  Bilal     76   19
3   Hina     89   22

In [172]:
# 1. Select row with label 2
print(df.loc[2])

Name     Bilal
Marks       76
Age         19
Name: 2, dtype: object

In [173]:
# 2. Select specific rows and columns by NAME
print(df.loc[1:3, ["Name", "Marks"]])

    Name  Marks
1   Sara     92
2  Bilal     76
3   Hina     89

In [174]:

# 3. Applying Filter: Conditional selection: students with Marks > 85
print(df.loc[df["Marks"] > 85])

   Name  Marks  Age
1  Sara     92   21
3  Hina     89   22

##  Slicing through iloc

In [175]:
df

    Name  Marks  Age
0    Ali     85   20
1   Sara     92   21
2  Bilal     76   19
3   Hina     89   22

In [176]:
# 1. Select row at index 0
print(df.iloc[0])

Name     Ali
Marks     85
Age       20
Name: 0, dtype: object

In [177]:
# 2. Select 2 rows and 2 columns by position
print(df.iloc[0:2, 0:2])

   Name  Marks
0   Ali     85
1  Sara     92

In [178]:
# 3. Select last row using negative index
print(df.iloc[-1])

Name     Hina
Marks      89
Age        22
Name: 3, dtype: object

# Dropping the Row

In [179]:
df

    Name  Marks  Age
0    Ali     85   20
1   Sara     92   21
2  Bilal     76   19
3   Hina     89   22

In [180]:
df.drop(0).head()

    Name  Marks  Age
1   Sara     92   21
2  Bilal     76   19
3   Hina     89   22

# Dropping the col

In [181]:
df.drop(['Age'], axis=1).head()

    Name  Marks
0    Ali     85
1   Sara     92
2  Bilal     76
3   Hina     89

In [182]:
df.head()

    Name  Marks  Age
0    Ali     85   20
1   Sara     92   21
2  Bilal     76   19
3   Hina     89   22

In [183]:
df.drop(['Age'], axis=1, inplace=True)

In [184]:
df.head()

    Name  Marks
0    Ali     85
1   Sara     92
2  Bilal     76
3   Hina     89

In [185]:
df.reset_index().head()

   index   Name  Marks
0      0    Ali     85
1      1   Sara     92
2      2  Bilal     76
3      3   Hina     89

In [186]:
df.reset_index(drop=True).head()

    Name  Marks
0    Ali     85
1   Sara     92
2  Bilal     76
3   Hina     89

In [187]:
df.head()

    Name  Marks
0    Ali     85
1   Sara     92
2  Bilal     76
3   Hina     89

In [188]:
df.reset_index(drop=True, inplace=True)

In [189]:
df.head()

    Name  Marks
0    Ali     85
1   Sara     92
2  Bilal     76
3   Hina     89

# Groupby
The groupby method allows you to group rows of data together and call aggregate functions

​
​

In [190]:
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [191]:
df = pd.DataFrame(data)

In [192]:
df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

### Now you can use the .groupby() method to group rows together based off of a column name.
For instance let's group based off of Company. This will create a DataFrameGroupBy object:

In [193]:
df.groupby('Company')

##### You can save this object as a new variable:

In [194]:
by_comp = df.groupby("Company")
type(by_comp)

pandas.api.typing.DataFrameGroupBy

#### And then call aggregate methods of the object:

In [195]:
by_comp.std(numeric_only=True)

              Sales
Company
FB        75.660426
GOOG      56.568542
MSFT     152.735065

In [196]:
df.groupby('Company').std(numeric_only=True)

              Sales
Company
FB        75.660426
GOOG      56.568542
MSFT     152.735065

In [197]:
by_comp.std(numeric_only=True)

              Sales
Company
FB        75.660426
GOOG      56.568542
MSFT     152.735065

In [198]:
by_comp.min()

          Person  Sales
Company
FB          Carl    243
GOOG     Charlie    120
MSFT         Amy    124

In [199]:
by_comp.max()

          Person  Sales
Company
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [200]:
by_comp.count()

         Person  Sales
Company
FB            2      2
GOOG          2      2
MSFT          2      2

In [201]:
by_comp.describe()

        Sales
        count   mean         std    min     25%    50%     75%    max
Company
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0